services:
  mysql:
    image: mysql:8.0
    container_name: air_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - air-network

  go-app:
    build: .
    container_name: air_go
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      AIR_PORT: 8181
    networks:
      - air-network
    volumes:
      - ./public:/app/public

  nginx:
    image: nginx:alpine
    container_name: air_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-cloudflare.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - go-app
    networks:
      - air-network

  adminer:
    image: adminer:latest
    container_name: air_adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - "8283:8080"
    networks:
      - air-network

networks:
  air-network:
    driver: bridge
